name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Fix Gradle Version & Build APK
        run: |
          PROJECT_DIR=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1 | xargs dirname)
          echo "Found project in: $PROJECT_DIR"
          cd "$PROJECT_DIR/android"

          # 1. Directly replace Gradle distribution URL to Gradle 8.4
          sed -i 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-8.4-bin.zip|g' gradle/wrapper/gradle-wrapper.properties

          # 2. Add flags to support AGP and Android SDK 34
          echo "android.suppressUnsupportedCompileSdk=34" >> gradle.properties
          echo "android.newDsl=false" >> gradle.properties

          cd ..
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: reelzy-app
          path: '**/build/app/outputs/flutter-apk/*.apk'
